name: Streamlit App Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      env:
        AZURE_GPT4V_KEY: ${{ secrets.AZURE_GPT4V_KEY }}
        AZURE_GPT4V_ENDPOINT: ${{ secrets.AZURE_GPT4V_ENDPOINT }}
        TEMPERATURE: ${{ secrets.TEMPERATURE }}
        TOP_P: ${{ secrets.TOP_P }}
        MAX_TOKENS: ${{ secrets.MAX_TOKENS }}
      run: |
        python -m pytest tests/
        
    - name: Deploy to Streamlit Cloud
      env:
        AZURE_GPT4V_KEY: ${{ secrets.AZURE_GPT4V_KEY }}
        AZURE_GPT4V_ENDPOINT: ${{ secrets.AZURE_GPT4V_ENDPOINT }}
      run: |
        echo "Deployment triggered"