[azure]
gpt4v_key = "0df571534be34d3fa5ac6dc8d9c2aa9e"
gpt4v_endpoint = "https://ohkimsai.openai.azure.com/openai/deployments/gpt-4o-ryumin/chat/completions?api-version=2024-02-15-preview"
temperature = "0.7"
top_p = "0.95"
max_tokens = "2000"